### ISSUE TITLE
`ghasum` as an Action

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/ghasum#4]
Depends on #2

## Summary

Make it convenient to run `ghasum` as part of a GitHub Actions workflow in order to continuously and at runtime check the integrity of the Actions in a workflow. To achieve this, I think it makes to most sense to offer `ghasum` as a GitHub Action.

### Example

```yaml
name: Example
on: [push]

jobs:
  example:
    name: example
    runs-on: ubuntu-latest
    steps:
    - name: Validate Actions Integrity
      uses: ericcornelissen/ghasum@v1.0.0
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    # Rest ...
```

## Goals

- The Action should validate the integrity of the actions used in the current job.
- Ideally this can validate the repositories as pulled by the GitHub Actions infrastructure.
